kind: pipeline
type: docker
name: default
   
steps:
- name: test
  image: alpine
  commands:
  - echo hello
  - echo world


# ---
# kind: pipeline
# type: docker
# name: homelab build

# steps:
#   - name: test
#     image: hello-world
#     trigger:
#       event:
#         - push
