version: "3.7"
services:
  docker-registry:
    image: registry:2
    restart: always
    ports:
      - 5000:5000
    volumes:
      - docker-registry-data:/var/lib/registry

volumes:
  docker-registry-data:
