version: "3.7"
services:
  drone-server:
    image: drone/drone:1
    ports:
      - 8000:80
    volumes:
      - drone-server-data:/var/lib/drone
    restart: always
    env_file:
      - secrets/drone-github-client.env
      - secrets/drone-github-secret.env
      - secrets/drone-rpc-secret.env
      # less a secret and more just a local setting
      - secrets/drone-user-filter.env
    environment:
      - DRONE_SERVER_HOST=pohara:8000
      - DRONE_SERVER_PROTO=http
      - DRONE_SERVER_PROXY_HOST=pohara.kitchen.io:5536

  docker-runner:
    image: drone/drone-runner-docker:1
    ports:
      - 3000:3000
    restart: always
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone-server:80
    env_file:
      - secrets/drone-rpc-secret.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  drone-server-data:
